# fly.toml file generated for egld-price-discord-bot on 2023-03-11T00:07:50+01:00

app = "egld-price-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"
processes = []

[env]

[experimental]
  auto_rollback = true

